### ISSUE TITLE
API URL was changed

### ISSUE THREAD

**Issue by vinniwain** [demyashev/market-scanner#1]
src/Model/HTTP/Request.php:10

`const URL = 'https://market-scanner.ru/api';` - it doesn't work now

need to change to

`const URL = 'https://ymscanner.ru/api';` - it works

**Comment by vinniwain** [comment]
> `const URL = 'https://ymscanner.ru/api';` - it works

or putting it to .env would be better

**Comment by demyashev** [comment]
In version 2.0, the address was changed
